### ISSUE TITLE
Spark submit fails when the config file is placed in AWS S3 and run in deploy mode

### ISSUE THREAD

**Issue by sudheer-chava** [YotpoLtd/metorikku#140]
I am trying to run the following spark-submit 

/home/ec2-user/spark_home/bin/spark-submit --class com.yotpo.metorikku.Metorikku --deploy-mode cluster --driver-memory 4g --executor-memory 50g --executor-cores 8  --master <master_host>:6066  metorikku.jar -c s3a://<bucket>/slice/metorikku_test.yaml

it failed with the following error message.

Error: Supplied YAML file not found
Try --help for more information.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.worker.DriverWrapper$.main(DriverWrapper.scala:65)
        at org.apache.spark.deploy.worker.DriverWrapper.main(DriverWrapper.scala)
Caused by: com.yotpo.metorikku.exceptions.MetorikkuException: Failed to parse config file
        at com.yotpo.metorikku.configuration.ConfigurationParser$.parse(ConfigurationParser.scala:20)
        at com.yotpo.metorikku.Metorikku$.delayedEndpoint$com$yotpo$metorikku$Metorikku$1(Metorikku.scala:15)
        at com.yotpo.metorikku.Metorikku$delayedInit$body.apply(Metorikku.scala:12)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at com.yotpo.metorikku.Metorikku$.main(Metorikku.scala:12)
        at com.yotpo.metorikku.Metorikku.main(Metorikku.scala)
        ... 6 more

when metorikku_test.yaml config file is placed locally it works absolutely fine. How to make config file (and metrics file be placed at a centralised location such as S3 so available at runtime?)

**Comment by RonBarabash** [comment]
Hi @sudheer-chava currently Metorikku does not support loading config files from s3, what we do is copy the files from s3 in the bootstrap script of the cluster.
It would be a nice addition to have Metorikku load these files automatically, maybe we will get to it somewhere in the future.. :)
10x
Ron

**Comment by lyogev** [comment]
Added #142 to support this

**Comment by sourav2050** [comment]
> I am trying to run the following spark-submit
> 
> /home/ec2-user/spark_home/bin/spark-submit --class com.yotpo.metorikku.Metorikku --deploy-mode cluster --driver-memory 4g --executor-memory 50g --executor-cores 8 --master <master_host>:6066 metorikku.jar -c s3a:///slice/metorikku_test.yaml
> 
> it failed with the following error message.
> 
> Error: Supplied YAML file not found
> Try --help for more information.
> Exception in thread "main" java.lang.reflect.InvocationTargetException
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.apache.spark.deploy.worker.DriverWrapper$.main(DriverWrapper.scala:65)
> at org.apache.spark.deploy.worker.DriverWrapper.main(DriverWrapper.scala)
> Caused by: com.yotpo.metorikku.exceptions.MetorikkuException: Failed to parse config file
> at com.yotpo.metorikku.configuration.ConfigurationParser$.parse(ConfigurationParser.scala:20)
> at com.yotpo.metorikku.Metorikku$.delayedEndpoint$com$yotpo$metorikku$Metorikku$1(Metorikku.scala:15)
> at com.yotpo.metorikku.Metorikku$delayedInit$body.apply(Metorikku.scala:12)
> at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
> at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
> at scala.App$$anonfun$main$1.apply(App.scala:76)
> at scala.App$$anonfun$main$1.apply(App.scala:76)
> at scala.collection.immutable.List.foreach(List.scala:381)
> at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
> at scala.App$class.main(App.scala:76)
> at com.yotpo.metorikku.Metorikku$.main(Metorikku.scala:12)
> at com.yotpo.metorikku.Metorikku.main(Metorikku.scala)
> ... 6 more
> 
> when metorikku_test.yaml config file is placed locally it works absolutely fine. How to make config file (and metrics file be placed at a centralised location such as S3 so available at runtime?)

Hi Sudheer,

Can you help me how did you do that. When I am using spark-submit command it is throwing error with file not found.
File does not exist: /home/hadoopuser/IdeaProjects/metorikku/examples/movies.yaml

**Comment by lyogev** [comment]
Can you share your full spark-submit command?

**Comment by sourav2050** [comment]
spark-submit --master local[*] --class com.yotpo.metorikku.Metorikku /home/hadoopuser/IdeaProjects/metorikku/target/scala-2.11/metorikku.jar -c /home/hadoopuser/IdeaProjects/metorikku/examples/movies.yaml
