### ISSUE TITLE
CSV file input causing java.lang.IllegalArgumentException: Illegal pattern component: XXX

### ISSUE THREAD

**Issue by ashcs85** [YotpoLtd/metorikku#163]
I am getting following exception when putting a csv file(comma separated values, also contains date time field as _09:27.9_) as file input in metorikku config yaml in our Spark cluster environment.
**Exception**: java.lang.IllegalArgumentException: Illegal pattern component: XXX

Could you please suggest any solution or workaround, thanks.

Stacktrace:
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.worker.DriverWrapper$.main(DriverWrapper.scala:65)
	at org.apache.spark.deploy.worker.DriverWrapper.main(DriverWrapper.scala)
Caused by: java.lang.IllegalArgumentException: Illegal pattern component: XXX
	at org.apache.commons.lang3.time.FastDateFormat.parsePattern(FastDateFormat.java:577)
	at org.apache.commons.lang3.time.FastDateFormat.init(FastDateFormat.java:444)
	at org.apache.commons.lang3.time.FastDateFormat.<init>(FastDateFormat.java:437)
	at org.apache.commons.lang3.time.FastDateFormat$1.createInstance(FastDateFormat.java:110)
	at org.apache.commons.lang3.time.FastDateFormat$1.createInstance(FastDateFormat.java:109)
	at org.apache.commons.lang3.time.FormatCache.getInstance(FormatCache.java:82)
	at org.apache.commons.lang3.time.FastDateFormat.getInstance(FastDateFormat.java:205)
	at org.apache.spark.sql.execution.datasources.csv.CSVOptions.<init>(CSVOptions.scala:136)
	at org.apache.spark.sql.execution.datasources.csv.CSVOptions.<init>(CSVOptions.scala:39)
	at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat.inferSchema(CSVFileFormat.scala:55)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$8.apply(DataSource.scala:203)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$8.apply(DataSource.scala:203)
	at scala.Option.orElse(Option.scala:289)
	at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:202)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:393)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
	at com.yotpo.metorikku.input.readers.file.FilesInput.read(FilesInput.scala:50)
	at com.yotpo.metorikku.input.readers.file.FileInput.read(FileInput.scala:15)
	at com.yotpo.metorikku.Job$$anonfun$registerDataframes$1.apply(Job.scala:69)
	at com.yotpo.metorikku.Job$$anonfun$registerDataframes$1.apply(Job.scala:67)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at com.yotpo.metorikku.Job.registerDataframes(Job.scala:67)
	at com.yotpo.metorikku.Job.<init>(Job.scala:49)
	at com.yotpo.metorikku.Metorikku$.delayedEndpoint$com$yotpo$metorikku$Metorikku$1(Metorikku.scala:10)
	at com.yotpo.metorikku.Metorikku$delayedInit$body.apply(Metorikku.scala:7)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at com.yotpo.metorikku.Metorikku$.main(Metorikku.scala:7)
	at com.yotpo.metorikku.Metorikku.main(Metorikku.scala)

**Comment by ashcs85** [comment]
Hi, 
Does anyone has inputs on this exception for csv file as input to Metorikku? 
Any help would be greatly appreciated, thanks.

**Comment by lyogev** [comment]
Can you check out #158 it looks very similar to that.
What I recommended there was an upgrade, but it will also help to get a sample of your CSV.
See also what the user did there to solve the issue.

Thanks

**Comment by ashcs85** [comment]
#158 is for Output csv file issue and its resolved and working. My issue is with Input csv file and I tried playing around the resolution for #158 as mentioned below but no success. 
_inputOptions:
            coalesce: true
            extraOptions:
              multiline: "true"
              timestampFormat: "yyyy-MM-dd'T'HH:mm:ss"_

The csv file contains comma delimited values having numbers and NULL and I even tried after removing the date fields having values like '09:27.9' but it didn't work. Is there any configuration we can do in Input section for csv file type?

**Comment by lyogev** [comment]
It will be really helpful if you sent some sample lines from your csv that
way I could debug this here.

But in any case I'm looking into this and hopefully I'll be able to help
later today.

**Comment by lyogev** [comment]
Try:
```
input:
  path: file.csv
  format: csv
  options:
    timestampFormat: "MM:ss.SSS"
```
In any case you need to play with the date format or do ```inferSchema: "false"```

**Comment by ashcs85** [comment]
Thanks a lot. Above solution worked, I tried below setting.

```
input:
  path: file.csv
  format: csv
  options:
    timestampFormat: "MM:ss.SSS"
```
