### ISSUE TITLE
Yesterday's Docker image for Hive 2.3.3 has corrupt Hadoop installation

### ISSUE THREAD

**Issue by jheinnic** [YotpoLtd/metorikku#303]
I have been unable to run the docker-compoose based integration test under `e2e/hive` today.  The hive container is failing to start, complaining about a non-existant class:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/mapred/JobConf
	at org.apache.hadoop.hive.conf.HiveConf.initialize(HiveConf.java:4045)
	at org.apache.hadoop.hive.conf.HiveConf.<init>(HiveConf.java:4003)
	at org.apache.hadoop.hive.common.LogUtils.initHiveLog4jCommon(LogUtils.java:81)
	at org.apache.hadoop.hive.common.LogUtils.initHiveLog4j(LogUtils.java:65)
	at org.apache.hive.service.server.HiveServer2.main(HiveServer2.java:716)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.mapred.JobConf
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
```

After creating an instance with a shell in lieu of its usual entry point, it seems like the Hadoop installation on this image has several 0-byte jar files where there should be genuine content.  The missing class, `org.apache.hadoop.mapred.JobConf`, above, should be classloaded from `hadoop-mapreduce-client-core-2.7.4.jar`, below...

```
root@5d74763f9421:/opt# ls -lal hadoop/share/hadoop/mapreduce/
total 20
drwxr-xr-x 5 20415 messagebus 4096 Aug  1  2017 .
drwxr-xr-x 9 20415 messagebus 4096 Aug  1  2017 ..
-rw-r--r-- 1 20415 messagebus    0 Aug  1  2017 hadoop-mapreduce-client-app-2.7.4.jar
-rw-r--r-- 1 20415 messagebus    0 Aug  1  2017 hadoop-mapreduce-client-common-2.7.4.jar
-rw-r--r-- 1 20415 messagebus    0 Aug  1  2017 hadoop-mapreduce-client-core-2.7.4.jar
-rw-r--r-- 1 20415 messagebus    0 Aug  1  2017 hadoop-mapreduce-client-hs-2.7.4.jar
-rw-r--r-- 1 20415 messagebus    0 Aug  1  2017 hadoop-mapreduce-client-hs-plugins-2.7.4.jar
-rw-r--r-- 1 20415 messagebus    0 Aug  1  2017 hadoop-mapreduce-client-jobclient-2.7.4-tests.jar
-rw-r--r-- 1 20415 messagebus    0 Aug  1  2017 hadoop-mapreduce-client-jobclient-2.7.4.jar
-rw-r--r-- 1 20415 messagebus    0 Aug  1  2017 hadoop-mapreduce-client-shuffle-2.7.4.jar
-rw-r--r-- 1 20415 messagebus    0 Aug  1  2017 hadoop-mapreduce-examples-2.7.4.jar
drwxr-xr-x 2 20415 messagebus 4096 Aug  1  2017 lib
drwxr-xr-x 2 20415 messagebus 4096 Aug  1  2017 lib-examples
drwxr-xr-x 2 20415 messagebus 4096 Aug  1  2017 sources
root@5d74763f9421:/opt# 
```

Comparing with the install directory storage size in S3 is also telling:

metorikku/hive:2.3.3
```
root@5d74763f9421:/opt# hadoop version
Hadoop 2.7.4
Subversion https://shv@git-wip-us.apache.org/repos/asf/hadoop.git -r cd915e1e8d9d0131462a0b7301586c175728a282
Compiled by kshvachk on 2017-08-01T00:29Z
Compiled with protoc 2.5.0
From source with checksum 50b0468318b4ce9bd24dc467b7ce1148
This command was run using /opt/hadoop/share/hadoop/common/hadoop-common-2.7.4.jar
root@5d74763f9421:/opt# du -sk /opt/hadoop
205644	/opt/hadoop
root@5d74763f9421:/opt# 
```

metorikku/hive:1.2.2:
```
root@3bd94f8f8d37:/opt# hadoop version
Hadoop 2.7.4
Subversion https://shv@git-wip-us.apache.org/repos/asf/hadoop.git -r cd915e1e8d9d0131462a0b7301586c175728a282
Compiled by kshvachk on 2017-08-01T00:29Z
Compiled with protoc 2.5.0
From source with checksum 50b0468318b4ce9bd24dc467b7ce1148
This command was run using /opt/hadoop/share/hadoop/common/hadoop-common-2.7.4.jar
root@3bd94f8f8d37:/opt# du -sk /opt/hadoop
509296	/opt/hadoop
```

The broke image was tagged with 2.3.3, and has the following digest:

```
REPOSITORY              TAG        DIGEST                                                                   IMAGE ID            CREATED             SIZE
metorikku/hive.         2.3.3      sha256:eaab14f4be04e38a857833120faa93b02031caca9afc15afd9e42b5bdf75b731  2701e49afa6c        3 weeks ago         1.18GB
```

**Comment by lyogev** [comment]
Thanks a lot for reporting this, I guess the docker cache got corrupted somehow, I'm going to try and release without cache.

**Comment by lyogev** [comment]
It's working now I believe

**Comment by jheinnic** [comment]
That did indeed do the trick, thanks!
