### ISSUE TITLE
Issue while running in Intellij IDE

### ISSUE THREAD

**Issue by aksashu000** [YotpoLtd/metorikku#419]
Getting below error when running through IDE:

21/05/07 12:24:37 INFO Metorikku$: Starting Metorikku - Parsing configuration
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/scheduler/SparkListenerInterface
	at com.yotpo.metorikku.Metorikku$.delayedEndpoint$com$yotpo$metorikku$Metorikku$1(Metorikku.scala:12)
	at com.yotpo.metorikku.Metorikku$delayedInit$body.apply(Metorikku.scala:9)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at com.yotpo.metorikku.Metorikku$.main(Metorikku.scala:9)
	at com.yotpo.metorikku.Metorikku.main(Metorikku.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.scheduler.SparkListenerInterface
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 11 more

**Comment by amirhalatzi** [comment]
Which JDK version are you using?

**Comment by aksashu000** [comment]
openjdk version "1.8.0_275

**Comment by aksashu000** [comment]
21/05/24 13:03:46 INFO Metorikku$: Starting Metorikku - Parsing configuration
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/scheduler/SparkListenerInterface
	at com.yotpo.metorikku.Metorikku$.delayedEndpoint$com$yotpo$metorikku$Metorikku$1(Metorikku.scala:12)
	at com.yotpo.metorikku.Metorikku$delayedInit$body.apply(Metorikku.scala:9)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1$adapted(App.scala:80)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.App.main(App.scala:80)
	at scala.App.main$(App.scala:78)
	at com.yotpo.metorikku.Metorikku$.main(Metorikku.scala:9)
	at com.yotpo.metorikku.Metorikku.main(Metorikku.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.scheduler.SparkListenerInterface
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 11 more

**Comment by aksashu000** [comment]
By the way, it's working fine in spark-submit mode. :)

**Comment by aksashu000** [comment]
I figured it out. I was able to run from IntelliJ when I changed the scope from provided to compile for two resources:

  "org.apache.spark" %% "spark-core" % sparkVersion.value % "compile",
  "org.apache.spark" %% "spark-sql" % sparkVersion.value % "compile"

Closing the issue. Thanks a lot for your help! :)
